### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [KamilFlis/python_makao#1]
1. Pylint jest Pana przyjacielem.
2. `CardValue` ma `Takie` elementy, a `CardSuit` `TAKIE`. Lepiej ujednolicić.
3. Chyba dopisywanie `.value` po każdym użyciu wartości enum-owej nie ma większego sensu. Czy próbował Pan zrobić `specialCards` itp. bez tego `.value`?
4. `specialCards` powinno się nazywać `special_cards`, a może nawet `SPECIAL_CARDS`, bo po zbudowaniu się nie zmienia, prawda? (2. rozdział Poradnika). Dla dodatkowego efektu może Pan dopisać `SPECIAL_CARDS = frozenset(SPECIAL_CARDS)` na końcu ich budowania.
5. [Ta metoda](https://github.com/KamilFlis/python_makao/blob/dc6809aeb4b209856bec26a82d73f3c35598f88d/venv/bin/src/makao.py#L107) mi się nie podoba. Czemu gra jest częścią każdego gracza, a nie na odwrót? Z postawienia tego na głowie zdają się wynikać nieeleganckie wygibasy na polach gracza (proszę się zapoznać z 4. rozdziałem Poradnika).
6. `if card_to_put_on_table[0] is len(self.hand):` — tak nie wolno. To działa tylko przez przypadek implementacyjny, polegający na tym że liczby do bodajże 127 żyją w jednej kopii. Liczby porównujemy przez `==`; `is` i `is not` są do porównywania singletonów, których jest [ledwie kilka](https://docs.python.org/3.8/library/constants.html).
7. Dwie drabinki if-ów (`value` i `suit`) w `make_restriction()` zastąpić przez użycie stałej listy lub stałego słownika.
8. W ogóle `make_restriction()` jest koszmarnie długie. Nadrzędną drabinkę if-ów od waleta po czwórkę zastąpić wywołaniami mniejszych metod, wybieranych według stałego słownika.
9. Plik `tests.py` przemianować na `makao_test.py`, użyć w nim `import makao` zamiast `from makao import *`, klasę `Tests` przemianować na `GameTest` i dopisać do niej
```python
def setUp(self):
    self.game = makao.Game()
```

**Comment by MarcinCiura** [comment]
Kolejne uwagi. Po ich uwzględnieniu proszę odpowiedzieć poniżej zamiast wysyłać email.
1. Importy posortować (2. rozdział).
2. Ścieżki sklejać nie plusami, tylko przez `os.path.join()` (3. rozdział). Nazwę z rozszerzeniem łączyć nie plusem, tylko przez f-string (2. rozdział).
3. [To 5](https://github.com/KamilFlis/python_makao/blob/71b4607983efff1aec2d7088ab223d08b60d23c2/venv/bin/src/makao.py#L194) nazwać.
4. `win_con()` to zła nazwa (skrót, 2. rozdział).
5. [Niepotrzebne wyjaśnienia](https://github.com/KamilFlis/python_makao/blob/71b4607983efff1aec2d7088ab223d08b60d23c2/venv/bin/src/makao_test.py#L73), `.assertEqual()` samo z siebie pisze coś podobnego. Gdyby były potrzebne, lepiej używać f-stringów niż sklejać napisy plusami (2. rozdział).
6. Kolory lepiej nazywać od zastosowania, nie od zawartości (2. rozdział).

**Comment by KamilFlis** [comment]
Uwzględniłem w projekcie Pana uwagi.

**Comment by KamilFlis** [comment]
Dodałem możliwość położenia przez gracza kilku kart na raz oraz wyświetlenie informacji o grze. Myślę, że gra jest gotowa.

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję, jest Pan dwudziesty szósty.

W wolnej chwili: w `os.path.join()` pierwsze `'.'` są zbędne. W ogóle prościej by było zamiast tych `os.path.join()` pisać po prostu `'img/info.png'` itp.; tak, jak jest, miałoby pewien (nikły) sens tylko wtedy, gdyby z `'img'` zrobić stałą.

Dodatkowa prośba: jeśli nikt tego przed Panem nie zrobi, proszę ogłosić konsultacje w niedzielę o 20:30 i w poniedziałek o 12:00 pod standardowym linkiem. Dziękuję!
